### ISSUE TITLE
Make sure scrapers contain an id column

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/compare_with_wikidata#1]
At the moment we're just assuming a scraper has an `id` column. We should instead check for an ID column and if there isn't one then we should fail fast and give a clear error message.

**Comment by chrismytton** [comment]
This might be affected by the solution to #12, in that we'll need to make sure that the scraper contains all the columns that we want to compare against.

**Comment by lucychambers** [comment]
Won't fix

**Comment by tmtmtmtm** [comment]
superseded by #12
