### ISSUE TITLE
Edits should have a bot flag on them

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/compare_with_wikidata#119]
We got [a message](https://www.wikidata.org/wiki/User_talk:Chris_Mytton?markasread=222280963#Bot_flag) telling us that the edits Prompter Bot is making don't have the bot flag on them.

Looking at https://www.mediawiki.org/wiki/Manual:Bots it seems that even though the `Prompter Bot` user is a bot user that doesn't mean edits will automatically get the bot flag. We need to _also_ add the bot flag to edits. We're using the [`mediawiki_api` Rubygem](https://github.com/wikimedia/mediawiki-ruby-api), so we need to figure out where in that we need to set the bot flag.

**Comment by tmtmtmtm** [comment]
Presumably this will also be true for our other bots too (https://github.com/everypolitician/wikidata-position-history, https://github.com/everypolitician/position_statements)? As it's highly likely that we'll end up with more, it might be worth thinking about a way to make sure we always remember this (e.g. a thin wrapper of our own around `mediawiki_api` for our bots that sets this by default)

**Comment by chrismytton** [comment]
Good point. We might need to do something a bit different for `position_statements`, since that's written with Pywikibot, rather than `mediawiki_api`. But for `wikidata-position-history` I agree that a wrapper around `mediawiki_api` might be a sensible way to go.

One thing I'm not sure about is if we still want to support people running these bots using their own account? If we do then I suppose the bot flag should only be set when the account making the edits is a bot user account. Not sure if there's a way to detect that, or whether we should make the bot flag another configuration value?

**Comment by tmtmtmtm** [comment]
Closed by #131, though we still need to look into this for other tools.
