### ISSUE TITLE
Handle comparing on multiple values

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/compare_with_wikidata#12]
At the moment we're just comparing two lists based on the Wikidata identifier. It would be good if we could compare on multiple values, e.g. Wikidata ID + name, or for [Heads of Government](https://morph.io/everypolitician-scrapers/heads-of-government-wikipedia) we'd want to compare on the triple (country, office, office holder).

**Comment by lucychambers** [comment]
Suggestion: Only solve for the specific cases as you come across them.

**Comment by chrismytton** [comment]
This was fixed by switching to daff for comparisons. See #19 and #20.
