### ISSUE TITLE
Example case: Heads of Government

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/compare_with_wikidata#14]
We have a variety of reports to make sure that the Heads of Government information in Wikidata is _consistent_ across three different ways it could be added. However, if a country gets a new HoG, and no-one updates any of those three in Wikidata, it will be consistently wrong. So we also scrape the [Wikipedia "Heads of State and Government" page](https://en.wikipedia.org/wiki/List_of_current_heads_of_state_and_government) to https://morph.io/everypolitician-scrapers/heads-of-government-wikipedia, and want to be able to compare that against what's in Wikidata:

```sparql
SELECT DISTINCT ?item ?itemLabel ?office ?officeLabel ?officeholder ?officeholderLabel
WHERE { 
  ?item wdt:P31 wd:Q6256 . 
  OPTIONAL { 
    ?item wdt:P1313 ?office . 
    OPTIONAL { ?office wdt:P1308 ?officeholder . } 
  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
}
ORDER BY ?itemLabel
```

[Try it!](https://query.wikidata.org/#SELECT%20DISTINCT%20%3Fitem%20%3FitemLabel%20%3Foffice%20%3FofficeLabel%20%3Fofficeholder%20%3FofficeholderLabel%0AWHERE%20%7B%20%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ6256%20.%20%0A%20%20OPTIONAL%20%7B%20%0A%20%20%20%20%3Fitem%20wdt%3AP1313%20%3Foffice%20.%20%0A%20%20%20%20OPTIONAL%20%7B%20%3Foffice%20wdt%3AP1308%20%3Fofficeholder%20.%20%7D%20%0A%20%20%7D%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20.%20%7D%0A%7D%0AORDER%20BY%20%3FitemLabel)

**Comment by tmtmtmtm** [comment]
An acceptable sub-story here would report solely on which people have been added/removed, but the fuller version should be able to show the country+office as well.

**Comment by chrismytton** [comment]
[Example of comparing the Wikipedia page with the SPARQL query using `daff`](https://cdn.rawgit.com/chrismytton/1c94fdcfad9aa11cbe2472a74176ac4b/raw/835a07265fe2d68857dacd88e63f1313c74b7e61/daff-output.html).
