### ISSUE TITLE
Enable comparison of fields

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/compare_with_wikidata#17]
Often the upstream change we want to be able to detect will not simply be a member completely appearing or vanishing, but one of the data fields changing (e.g. if they switch to a new political group/party/faction). 

It should be possible for the creator of a prompt to specify fields they wish to compare like this, and be notified when those differ upstream from what's in Wikidata.

**Comment by chrismytton** [comment]
This has now been taken care of by switching to daff. #19 and #20
