### ISSUE TITLE
Make this work without a command line

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/compare_with_wikidata#29]
Currently this library has to be run from the command line. Ideally it would be more like [listeria](http://tools.wmflabs.org/listeria/), which has a "Manually update list" button on reports which triggers an HTTP handler to update the page, e.g. see [Wikidata:WikiProject Heads of state and government/Report:P6](https://www.wikidata.org/wiki/Wikidata:WikiProject_Heads_of_state_and_government/Report:P6).

**Comment by lucychambers** [comment]
Successful completion of US Senate will "close" this ticket.

**Comment by lucychambers** [comment]
@chrismytton - just checking my understanding here: does this mean that the US senate is now possible? Happy to close this if this is generally able to work as we have a separate US senate ticket, but just checking whether the comment above still applies!

**Comment by chrismytton** [comment]
> Successful completion of US Senate will "close" this ticket.

@lucychambers I can't quite remember the context of this comment, but no, I think the US Senate ticket is still blocked on #40, but that should hopefully be fixed/avoided once I've finished https://github.com/everypolitician/compare_with_wikidata/pull/42, which I'm hoping to get done today.

**Comment by lucychambers** [comment]
Excellent!

**Comment by chrismytton** [comment]
This now works without a command line via https://github.com/everypolitician/everypolitician-prompts, which is an HTTP adapter to this library. It's currently hosted on Heroku but we're seeing the following error when trying to edit from Heroku:

> Your IP address is in a range which has been blocked on all wikis.‘’' The block was made by [//meta.wikimedia.org/wiki/User:Masti Masti] (meta.wikimedia.org). The reason given is ‘’[[m:NOP|Open proxy]]‘’. * Start of block: 12:43, 21 July 2017 * Expiration of block: 12:43, 21 July 2018 You can contact [//meta.wikimedia.org/wiki/User:Masti Masti] to discuss the block. You cannot use the “Email this user” feature unless a valid email address is specified in your [[Special:Preferences|account preferences]] and you have not been blocked from using it. Your current IP address is 54.170.8.142, and the blocked range is 54.170.0.0/16. Please include all above details in any queries you make. (globalblocking-ipblocked-range)

I think the solution to _that_ problem will be moving to Toolforge, which is tracked by #36.

I'm going to close this ticket, as it's done. We can track progress on US Senate in #15 and #40
