### ISSUE TITLE
Refresh prompts at a regular interval

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/compare_with_wikidata#34]
At the moment the prompts have to be manually refreshed by clicking the "Refresh this prompt". It would be good to have the prompts refreshed at a regular interval, following [Listeria's](http://tools.wmflabs.org/listeria/) model.

- How often do we want to refresh the prompts?
- Which API call do we need to use to find all pages using the prompt template?

**Comment by lucychambers** [comment]
Can be done manually, but we should also automate. 

## Acceptance Criteria 

* Lucy and Tony should be able to set up a new prompt and it should update daily. (Note: At the moment, we are setting up prompts only for countries that either have a Wikidata ID or an external ID until we decide how to tackle #38.)

**Comment by tmtmtmtm** [comment]
Toolforge might give us this essentially for free.

**Comment by chrismytton** [comment]
https://wikitech.wikimedia.org/wiki/Help:Toolforge/Grid#Scheduling_jobs_at_regular_intervals_with_cron

**Comment by lucychambers** [comment]
If it is a couple of hours work - let's do pre-launch. If not, let's talk.

**Comment by chrismytton** [comment]
This is now setup on Toolforge.

In order to install the crontab I ran the following commands:

```
$ become prompter
$ crontab -e
```

Then I added the following crontab entry, which refreshes all prompts at 09:00 UTC:

```
0 9 * * *  /usr/bin/jsub -N cron-tools.prompter-1 -once -quiet /data/project/prompter/prompter/script/toolforge-cronjob
```

I've also added these details to [the Wikitech/Tool:Prompter](https://wikitech.wikimedia.org/wiki/Tool:Prompter#Refreshing_prompts_regularly_with_cron) article.

**Comment by tmtmtmtm** [comment]
Yay.

OOI, why did you pick 09:00 UTC?

**Comment by chrismytton** [comment]
> OOI, why did you pick 09:00 UTC?

Simply because it was around 08:50 when I was testing it yesterday, so I just rounded it up! I'm happy to change when it runs if there's a time that's obviously better.

I suppose one small advantage of it running at 09:00 is that any cron errors that occur on working days can be quickly picked up and fixed.

**Comment by lucychambers** [comment]
Any objections or counter-suggestions?
