### ISSUE TITLE
Investigate hosting on Wikimedia Toolforge

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/compare_with_wikidata#36]
We should host this tool on [Wikimedia Toolforge](https://tools.wmflabs.org/).

- [x] Investigate what needs to be done to get this setup, e.g. getting an LDAP account etc.

**Comment by chrismytton** [comment]
I've registered for a toolforge account by following [the getting started guide](https://wikitech.wikimedia.org/wiki/Help:Getting_Started). I've also requested access to the "Tool Labs project", which is an option once you've registered and signed into a toolforge account.

Once I've got an account I should be able to SSH in and have a look at how to get compare with wikidata running on there.

**Comment by chrismytton** [comment]
The [Help:Toolforge/Web](https://wikitech.wikimedia.org/wiki/Help:Toolforge/Web) page looks like it will be useful when it comes to running the HTTP component on Toolforge.

**Comment by tmtmtmtm** [comment]
We now have an account, so #43 takes care of actually moving to it.
