### ISSUE TITLE
Move to Wikimedia infrastructure

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/compare_with_wikidata#43]
Need to follow the instructions at [Help:Toolforge/Web](https://wikitech.wikimedia.org/wiki/Help:Toolforge/Web) to get this app deployed onto Wikimedia's infrastructure.

**Comment by tmtmtmtm** [comment]
Following from #36

**Comment by chrismytton** [comment]
This is now up and running at https://tools.wmflabs.org/prompter 🎉 

Other related tasks that are outstanding are in their own tickets:

- Document compare_with_wikidata https://github.com/everypolitician/compare_with_wikidata/issues/44
- Update Wikitech with details on prompter deployment https://github.com/everypolitician/prompter/issues/2
- Add some developer docs to the prompter repo https://github.com/everypolitician/prompter/issues/3
