### ISSUE TITLE
Improve "new prompt" experience

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/compare_with_wikidata#58]
Currently, when I set up a new prompt, the page I get looks like:

![screen shot 2017-08-18 at 07 26 01](https://user-images.githubusercontent.com/57483/29446874-912225d8-83e6-11e7-86d7-20081251de57.png)

There are a few ways this could be improved:

1. Reverse the order of the CSV and SPARQL input.
* The expected workflow here is more likely going to be involve someone pointing at an external CSV file (possibly one that isn't even under their control), and then trying to generate a SPARQL query to match. So stepping them through setting it up like that is probably going to give the best experience.

2. Add some introductory text.
* This all appears simply by someone including `{{Compare Wikidata with CSV}}`. This is generally going to be quite unexpected, as this "Wizard"-based approach is quite unusual. So it would good if we could be even more explicit about what this tool *is*/*does*, as well as what we're expecting people to fill in. Some of that might be a link out to the help page(s), but we can undoubtedly do more to smooth the initial process here.
 
3. Defer the 'refresh' links until appropriate.
* Currently there are two "refresh this prompt" links on the page — one of them being the *first* link. As clicking either of these will trigger an error, it would be much nicer if we could hide them until both inputs are set.

**Comment by zarino** [comment]
Maybe we go all-out with the "wizard" concept, and literally show a sequence of setup steps?

Start with something like:

> It’s great that you want to compare Wikidata with a CSV. To get started, you need to complete the following 3 steps:

And then have the instructions we’ve already got, except under numbered headings, and with the CSV step first.

I wonder whether, for each step, we could link to an example from another, already working prompt? So when we say "add a CSV URL" (which is just a link to create a blank template), we could also give a "see an example" link that links to an existing `/csv_url` file somewhere else? Because how else are people going to know what to put in `/csv_url` and `/sparql`?

**Comment by zarino** [comment]
Ok @tmtmtmtm we’ve "wizardized" the setup steps, making it much more obvious what to do when you first set up the comparison.

![screen shot 2017-08-18 at 16 42 53](https://user-images.githubusercontent.com/739624/29466337-701e37d4-8434-11e7-9bfb-0a5c5d5dfd36.png)

The final button is disabled until you’ve completed steps 1 and 2.

Once you’ve generated the comparison the first time, the comparison table appears at the top of the page, and the "information" message disappears…

![screen shot 2017-08-18 at 16 49 56](https://user-images.githubusercontent.com/739624/29466594-575f9ab6-8435-11e7-90fc-fae8e4ff9f32.png)

And the setup steps shuffle down to the end of the page, and are joined by a few handy admin links for further customisation…

![screen shot 2017-08-18 at 16 50 03](https://user-images.githubusercontent.com/739624/29466621-7c18b05e-8435-11e7-8b21-f43020dbcb88.png)
