### ISSUE TITLE
Reported row counts include header row

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/compare_with_wikidata#60]
https://www.wikidata.org/wiki/User:Oravrattas/prompts/Riigikogu reports:

```
Total Wikidata items returned by SPARQL query: 108
Total Rows in CSV: 102
```

These are both inflated by one, presumably as they include the header row. 

(Strictly the "total rows in CSV" is actually correct, but #53 could be likely to make it incorrect! :) Either way it's a bit misleading)

**Comment by chrismytton** [comment]
This was (inadvertently!) fixed by https://github.com/everypolitician/compare_with_wikidata/pull/70 because that PR switched to getting CSVs as a Hash, rather than an Array.
