### ISSUE TITLE
Error: Illegal quoting in line 8.

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/compare_with_wikidata#62]
https://www.wikidata.org/wiki/User:Oravrattas/prompts/Riigikogu_13_EveryPolitician is currently failing with "Error: Illegal quoting in line 8."

(I haven't yet updated the SPARQL query to cast the IDs to strings rather than URLs, so I don't know whether this is factor or not, but I'm going to leave this as is for now to help track down the error)

**Comment by chrismytton** [comment]
@tmtmtmtm It looks like you're just linking to an HTML gist page, rather than an actual CSV file?

**Comment by chrismytton** [comment]
I think we should probably check for this specific error and give a helpful error message along the lines of "<URL> doesn't appear to point to a CSV file".

**Comment by tmtmtmtm** [comment]
> It looks like you're just linking to an HTML gist page 

Ah, yes, indeed. It would definitely be useful to give an error that points in the right direction, as I can even see myself doing this again, never mind other people!
