### ISSUE TITLE
Make 'admin' functions more distinct/separate.

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/compare_with_wikidata#63]
Once a prompt is running, the page contains a mix of data, explanatory text (currently mostly built in, but potentially bespoke too, post-#61), and ways of re-configuring the prompt. 

It would be good if "prompt administrator" tools (e.g. re-editing the SPARQL/CSV/templates etc) were kept more visually distinct from the parts that useful to someone who's primarily only using the prompt output.

**Comment by chrismytton** [comment]
This is now fixed.
