### ISSUE TITLE
Make 'refresh' more obviously an action

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/compare_with_wikidata#64]
'Refresh this prompt' is really an action, rather than a simple link, so it would be better to make it more obviously different (e.g. a button)

**Comment by zarino** [comment]
I don’t think there’s anything I can do to style a link or an `<a>` element on wikidata.org.

I _could_ wrap the link in a `<div>` that we then apply styles to. So, we could make _the div_ look like a button – but annoyingly, even though the entire div will then look like a button, only the _text_ part of it (ie: the link element inside) will _actually_ be clickable. Which might confuse people even more. What do you think?

**Comment by zarino** [comment]
For example, with some markup like this:

```
<u style="background-color: #f8f9fa; border: 1px solid #a2a9b1; padding: 0.5em 1em; border-radius: 2px; font-weight: bold; text-decoration: none;">[https://example.com Refresh this prompt]</u>
```

We could make something that looks like this:

![refresh](https://user-images.githubusercontent.com/739624/29457394-e22927ee-8411-11e7-83b1-99a99c38ed28.gif)

It doesn’t work _quite_ like a button, but maybe it’s good enough?

**Comment by tmtmtmtm** [comment]
@zarino perhaps we could use https://www.wikidata.org/wiki/Template:Clickable_button ?

**Comment by zarino** [comment]
@tmtmtmtm well spotted! I’ve added a `{{Clickable button}}` to https://www.wikidata.org/wiki/Template:Compare_Wikidata_with_CSV so it should appear on prompt pages when they next get regenerated.

**Comment by tmtmtmtm** [comment]
@zarino I think we need to do a little more to make it stand out. At the moment it's a little bit too dissimilar to the "Contents" section immediately below:

![screen shot 2017-08-18 at 14 52 30](https://user-images.githubusercontent.com/57483/29461803-f62286b0-8424-11e7-82bc-6c9fe0c68cc7.png)

Perhaps changing colour, or moving it to a different place, or making it bigger, or some combination of these might be enough, but I think it needs to be something that stands out more — both as "this is a big disruptive thing to do" when simply scanning the page, and also as being able to spot it at a glance when you're trying to remember how to refresh the data.

**Comment by zarino** [comment]
I was assuming that https://github.com/everypolitician/compare_with_wikidata/issues/63 would move it away from the top of the page!

**Comment by zarino** [comment]
We’ve moved the button to the bottom of the page, as part of the "wizardization" in https://github.com/everypolitician/compare_with_wikidata/issues/63 and https://github.com/everypolitician/compare_with_wikidata/issues/58. Let me know what you think!

**Comment by chrismytton** [comment]
Done as part of #63
