### ISSUE TITLE
Full Wikidata URLs expand oddly

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/compare_with_wikidata#65]
In https://www.wikidata.org/wiki/User:Oravrattas/prompts/Riigikogu_13_EveryPolitician, the SPARQL query doesn't convert the IDs to strings, so these are getting returned as e.g. http://www.wikidata.org/entity/Q12358429

The `Q` part of these is then getting expanded separately, leading to some rather odd output

![screen shot 2017-08-18 at 10 27 46](https://user-images.githubusercontent.com/57483/29452949-e8e9a908-83ff-11e7-8371-fabed791815e.png)

Ideally the code that converts `Q12358429` into `{{Q|12358429}}` would also Do The Right Thing with the full URL version too, so that the SPARQL-query-writer doesn't need to do the awkward coercion dance, but if that's too complex for now, we should anchor the substitution better.

**Comment by tmtmtmtm** [comment]
Hmmm. Actually, this is probably going to need to be solved at a different level, as if we only do this at output, we'll get lots of rows that appear to be diffless diffs. (Urmas Kruuse (Q3741429)->Urmas Kruuse (Q3741429))

**Comment by chrismytton** [comment]
This has now been fixed and deployed, so the Riigikogu should hopefully be less odd now.
