### ISSUE TITLE
Make clearer not to edit the template

### ISSUE THREAD

**Issue by lucychambers** [everypolitician/compare_with_wikidata#67]
Context: Attempting to set up my first prompt here - https://www.wikidata.org/wiki/User:Lucyfediachambers/sandbox/Daff_UK_Twitter

Feedback: When first setting up the prompt, the instructions were clear enough to follow. When however I needed to go back and edit the SPARQL - I accidentally edited the template (because I clicked the "edit" taking me to: https://www.wikidata.org/w/index.php?title=Template:Compare_Wikidata_with_CSV&action=edit&section=T-1 rather than the "Edit SPARQL for this prompt".)

![screen shot 2017-08-18 at 12 49 44](https://user-images.githubusercontent.com/1029861/29457916-796f6742-8414-11e7-9149-931ab507ec9e.png)

**Comment by chrismytton** [comment]
Looks like this might be useful: https://www.mediawiki.org/wiki/Manual:Section_editing

**Comment by tmtmtmtm** [comment]
This no longer seems to be a problem.
