### ISSUE TITLE
How to permanently blank a row template?

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/compare_with_wikidata#71]
When I wanted to remove the `+++` and/or `---` lines from a prompt, I started out by deleting the contents of those templates. But when I refreshed the prompt, they returned again.

The right way to do this at the minute seems to be to leave the comment in the template intact, so that the tool knows not to bring back the default. This should at least be more explicitly explained, but we might want to think about a nicer approach more generally.

**Comment by lucychambers** [comment]
Short term fix: expand hidden comment for the field. Improve wording.

**Comment by chrismytton** [comment]
Add some extra text to the existing comment:

> If you want to leave this template blank then delete everything except this comment.
