### ISSUE TITLE
Sort bot requirements

### ISSUE THREAD

**Issue by lucychambers** [everypolitician/compare_with_wikidata#72]
As per message from GZWDer‬.
Community needs to approve the bot. Need a set of things to show community what people can do using the bot.

**Comment by chrismytton** [comment]
https://www.wikidata.org/wiki/Wikidata:Bots

**Comment by mhl** [comment]
We've made a request for approval here: https://www.wikidata.org/wiki/Wikidata:Requests_for_permissions/Bot#Prompter_Bot

**Comment by lucychambers** [comment]
Email received: "Your user rights were changed. You have been added to: ‪Bots‬."

**Comment by chrismytton** [comment]
Done: https://www.wikidata.org/wiki/Wikidata:Requests_for_permissions/Bot/Prompter_Bot
