### ISSUE TITLE
Arrows shouldn't linebreak

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/compare_with_wikidata#80]
![screen shot 2017-08-30 at 17 20 55](https://user-images.githubusercontent.com/57483/29883283-ba395d9a-8da7-11e7-8a57-d2a7cd638717.png)

**Comment by chrismytton** [comment]
We can potentially avoid this issue in the default templates if we fix https://github.com/everypolitician/compare_with_wikidata/issues/81.
