### ISSUE TITLE
Q-id not being expanded

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/compare_with_wikidata#97]
On https://www.wikidata.org/wiki/User:Oravrattas/prompts/Riigikogu, Toomas Väinaste's district isn't being expanded from `Q3485728` to `{{Q|3485728}}`

**Comment by mhl** [comment]
This is deployed now as well, so if you refresh the prompt this should be fixed.

**Comment by tmtmtmtm** [comment]
Wahey!

![screen shot 2017-09-26 at 15 30 21](https://user-images.githubusercontent.com/57483/30865867-aaa41b44-a2cf-11e7-854f-8e4688841ef6.png)

Thanks @mhl
